/**
 * Donnees de demonstration utilisees quand le backend est hors ligne.
 */
import type { Product } from './api';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Elixir de Nuit',
    description: 'Parfum de peau au sillage boise, musque et velours. Pense pour les soirs ou l\'on veut marquer l\'instant sans jamais en faire trop.',
    price: 89,
    stock: 25,
    category: 'Parfums',
    image: 'https://images.unsplash.com/photo-1544467328-345179a4573b?auto=format&fit=crop&q=80&w=1200',
    is_new: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Huile de Soie',
    description: 'Huile de massage satinee enrichie en notes florales chaudes pour les rituels de couple et les soins du soir.',
    price: 45,
    stock: 30,
    category: 'Huiles',
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&q=80&w=1200',
    is_new: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Body Dentelle Androgyne',
    description: 'Piece de lingerie couture a la coupe epuree, pour une silhouette magnetique et assumee.',
    price: 110,
    stock: 15,
    category: 'Ensembles',
    image: 'https://images.unsplash.com/photo-1512446813985-4a0eb139016c?auto=format&fit=crop&q=80&w=1200',
    is_new: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Ensemble Soie Reine de Nuit',
    description: 'Ensemble deux pieces en soie noire et finitions dorees pour les moments de confidence et de ceremonie privee.',
    price: 165,
    stock: 10,
    category: 'Ensembles',
    image: 'https://images.unsplash.com/photo-1590156221122-c2947475700b?auto=format&fit=crop&q=80&w=1200',
    is_new: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Dual Fusion',
    description: 'Accessoire haut de gamme, ultra silencieux, waterproof et rechargeable. Pense pour une experience fluide, moderne et rassurante.',
    price: 195,
    stock: 20,
    category: 'Accessoires',
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&q=80&w=1200',
    is_new: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Harnais Obsidian',
    description: 'Cuir noir souple, boucles colorees or vieilli, presence visuelle forte. Piece de niche pour un vestiaire de nuit affirme.',
    price: 210,
    stock: 8,
    category: 'Accessoires',
    image: 'https://images.unsplash.com/photo-1519415387722-a1c3bbef716c?auto=format&fit=crop&q=80&w=1200',
    is_new: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Bougie Massage Ambre Rose',
    description: 'Bougie sensorielle qui se transforme en huile de massage tiede. Ideale pour les rituels lents et les cadeaux de couple.',
    price: 55,
    stock: 40,
    category: 'Soins',
    image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&q=80&w=1200',
    is_new: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Protection Satin Pure Confort',
    description: 'Confort premium, textile satine et discret pour prolonger la douceur des nuits sans compromis sur l\'elegance.',
    price: 45,
    stock: 50,
    category: 'Confort',
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&q=80&w=1200',
    is_new: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Coffret Premiere Nuit',
    description: 'Selection cadeau avec huile, bougie et accessoire doux. Une entree premium dans l\'univers LuxeSensuel.',
    price: 129,
    stock: 12,
    category: 'Coffrets',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=1200',
    is_new: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Brume Satin Nude',
    description: 'Brume de linge et de peau pour preparer une ambiance plus tactile, plus chic et plus enveloppante.',
    price: 39,
    stock: 18,
    category: 'Rituels',
    image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&q=80&w=1200',
    is_new: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '11',
    name: 'Lingerie Signature Minuit',
    description: 'Silhouette taille haute, transparence maitrisee et coupe editoriale. Une niche mode pour les clientes qui veulent du caractere.',
    price: 149,
    stock: 9,
    category: 'Lingerie',
    image: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&q=80&w=1200',
    is_new: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '12',
    name: 'Kit Couple Velours',
    description: 'Kit scenario intime avec accessoires doux et huiles chauffantes. Concu pour une experience de couple plus ludique et plus premium.',
    price: 175,
    stock: 6,
    category: 'Couples',
    image: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=1200',
    is_new: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];
