export interface Country {
  name: string;
  code: string;
  prefix: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", code: "AF", prefix: "+93", flag: "🇦🇫" },
  { name: "Afrique du Sud", code: "ZA", prefix: "+27", flag: "🇿🇦" },
  { name: "Albanie", code: "AL", prefix: "+355", flag: "🇦🇱" },
  { name: "Algérie", code: "DZ", prefix: "+213", flag: "🇩🇿" },
  { name: "Allemagne", code: "DE", prefix: "+49", flag: "🇩🇪" },
  { name: "Andorre", code: "AD", prefix: "+376", flag: "🇦🇩" },
  { name: "Angola", code: "AO", prefix: "+244", flag: "🇦🇴" },
  { name: "Anguilla", code: "AI", prefix: "+1-264", flag: "🇦🇮" },
  { name: "Antarctique", code: "AQ", prefix: "+672", flag: "🇦🇶" },
  { name: "Antigua-et-Barbuda", code: "AG", prefix: "+1-268", flag: "🇦🇬" },
  { name: "Arabie saoudite", code: "SA", prefix: "+966", flag: "🇸🇦" },
  { name: "Argentine", code: "AR", prefix: "+54", flag: "🇦🇷" },
  { name: "Arménie", code: "AM", prefix: "+374", flag: "🇦🇲" },
  { name: "Aruba", code: "AW", prefix: "+297", flag: "🇦🇼" },
  { name: "Australie", code: "AU", prefix: "+61", flag: "🇦🇺" },
  { name: "Autriche", code: "AT", prefix: "+43", flag: "🇦🇹" },
  { name: "Azerbaïdjan", code: "AZ", prefix: "+994", flag: "🇦🇿" },
  { name: "Bahamas", code: "BS", prefix: "+1-242", flag: "🇧🇸" },
  { name: "Bahreïn", code: "BH", prefix: "+973", flag: "🇧🇭" },
  { name: "Bangladesh", code: "BD", prefix: "+880", flag: "🇧🇩" },
  { name: "Barbade", code: "BB", prefix: "+1-246", flag: "🇧🇧" },
  { name: "Belgique", code: "BE", prefix: "+32", flag: "🇧🇪" },
  { name: "Belize", code: "BZ", prefix: "+501", flag: "🇧🇿" },
  { name: "Bénin", code: "BJ", prefix: "+229", flag: "🇧🇯" },
  { name: "Bermudes", code: "BM", prefix: "+1-441", flag: "🇧🇲" },
  { name: "Bhoutan", code: "BT", prefix: "+975", flag: "🇧🇹" },
  { name: "Biélorussie", code: "BY", prefix: "+375", flag: "🇧🇾" },
  { name: "Bolivie", code: "BO", prefix: "+591", flag: "🇧🇴" },
  { name: "Bosnie-Herzégovine", code: "BA", prefix: "+387", flag: "🇧🇦" },
  { name: "Botswana", code: "BW", prefix: "+267", flag: "🇧🇼" },
  { name: "Brésil", code: "BR", prefix: "+55", flag: "🇧🇷" },
  { name: "Brunéi Darussalam", code: "BN", prefix: "+673", flag: "🇧🇳" },
  { name: "Bulgarie", code: "BG", prefix: "+359", flag: "🇧🇬" },
  { name: "Burkina Faso", code: "BF", prefix: "+226", flag: "🇧🇫" },
  { name: "Burundi", code: "BI", prefix: "+257", flag: "🇧🇮" },
  { name: "Cambodge", code: "KH", prefix: "+855", flag: "🇰🇭" },
  { name: "Cameroun", code: "CM", prefix: "+237", flag: "🇨🇲" },
  { name: "Canada", code: "CA", prefix: "+1", flag: "🇨🇦" },
  { name: "Cap-Vert", code: "CV", prefix: "+238", flag: "🇨🇻" },
  { name: "Chili", code: "CL", prefix: "+56", flag: "🇨🇱" },
  { name: "Chine", code: "CN", prefix: "+86", flag: "🇨🇳" },
  { name: "Chypre", code: "CY", prefix: "+357", flag: "🇨🇾" },
  { name: "Colombie", code: "CO", prefix: "+57", flag: "🇨🇴" },
  { name: "Comores", code: "KM", prefix: "+269", flag: "🇰🇲" },
  { name: "Congo-Brazzaville", code: "CG", prefix: "+242", flag: "🇨🇬" },
  { name: "Congo-Kinshasa", code: "CD", prefix: "+243", flag: "🇨🇩" },
  { name: "Corée du Nord", code: "KP", prefix: "+850", flag: "🇰🇵" },
  { name: "Corée du Sud", code: "KR", prefix: "+82", flag: "🇰🇷" },
  { name: "Costa Rica", code: "CR", prefix: "+506", flag: "🇨🇷" },
  { name: "Côte d'Ivoire", code: "CI", prefix: "+225", flag: "🇨🇮" },
  { name: "Croatie", code: "HR", prefix: "+385", flag: "🇭🇷" },
  { name: "Cuba", code: "CU", prefix: "+53", flag: "🇨🇺" },
  { name: "Curaçao", code: "CW", prefix: "+599", flag: "🇨🇼" },
  { name: "Danemark", code: "DK", prefix: "+45", flag: "🇩🇰" },
  { name: "Djibouti", code: "DJ", prefix: "+253", flag: "🇩🇯" },
  { name: "Dominique", code: "DM", prefix: "+1-767", flag: "🇩🇲" },
  { name: "Égypte", code: "EG", prefix: "+20", flag: "🇪🇬" },
  { name: "Émirats arabes unis", code: "AE", prefix: "+971", flag: "🇦🇪" },
  { name: "Équateur", code: "EC", prefix: "+593", flag: "🇪🇨" },
  { name: "Érythrée", code: "ER", prefix: "+291", flag: "🇪🇷" },
  { name: "Espagne", code: "ES", prefix: "+34", flag: "🇪🇸" },
  { name: "Estonie", code: "EE", prefix: "+372", flag: "🇪🇪" },
  { name: "Eswatini", code: "SZ", prefix: "+268", flag: "🇸🇿" },
  { name: "États-Unis", code: "US", prefix: "+1", flag: "🇺🇸" },
  { name: "Éthiopie", code: "ET", prefix: "+251", flag: "🇪🇹" },
  { name: "Fidji", code: "FJ", prefix: "+679", flag: "🇫🇯" },
  { name: "Finlande", code: "FI", prefix: "+358", flag: "🇫🇮" },
  { name: "France", code: "FR", prefix: "+33", flag: "🇫🇷" },
  { name: "Gabon", code: "GA", prefix: "+241", flag: "🇬🇦" },
  { name: "Gambie", code: "GM", prefix: "+220", flag: "🇬🇲" },
  { name: "Géorgie", code: "GE", prefix: "+995", flag: "🇬🇪" },
  { name: "Ghana", code: "GH", prefix: "+233", flag: "🇬🇭" },
  { name: "Gibraltar", code: "GI", prefix: "+350", flag: "🇬🇮" },
  { name: "Grèce", code: "GR", prefix: "+30", flag: "🇬🇷" },
  { name: "Grenade", code: "GD", prefix: "+1-473", flag: "🇬🇩" },
  { name: "Groenland", code: "GL", prefix: "+299", flag: "🇬🇱" },
  { name: "Guadeloupe", code: "GP", prefix: "+590", flag: "🇬🇵" },
  { name: "Guam", code: "GU", prefix: "+1-671", flag: "🇬🇺" },
  { name: "Guatemala", code: "GT", prefix: "+502", flag: "🇬🇹" },
  { name: "Guernesey", code: "GG", prefix: "+44-1481", flag: "🇬🇬" },
  { name: "Guinée", code: "GN", prefix: "+224", flag: "🇬🇳" },
  { name: "Guinée équatoriale", code: "GQ", prefix: "+240", flag: "🇬🇶" },
  { name: "Guinée-Bissau", code: "GW", prefix: "+245", flag: "🇬🇼" },
  { name: "Guyane", code: "GY", prefix: "+592", flag: "🇬🇾" },
  { name: "Guyane française", code: "GF", prefix: "+594", flag: "🇬🇫" },
  { name: "Haïti", code: "HT", prefix: "+509", flag: "🇭🇹" },
  { name: "Honduras", code: "HN", prefix: "+504", flag: "🇭🇳" },
  { name: "Hong Kong", code: "HK", prefix: "+852", flag: "🇭🇰" },
  { name: "Hongrie", code: "HU", prefix: "+36", flag: "🇭🇺" },
  { name: "Île Bouvet", code: "BV", prefix: "", flag: "🇧🇻" },
  { name: "Île de Man", code: "IM", prefix: "+44-1624", flag: "🇮🇲" },
  { name: "Île Norfolk", code: "NF", prefix: "+672", flag: "🇳🇫" },
  { name: "Îles Caïmans", code: "KY", prefix: "+1-345", flag: "🇰🇾" },
  { name: "Îles Christmas", code: "CX", prefix: "+61", flag: "🇨🇽" },
  { name: "Îles Cocos", code: "CC", prefix: "+61", flag: "🇨🇨" },
  { name: "Îles Cook", code: "CK", prefix: "+682", flag: "🇨🇰" },
  { name: "Îles Féroé", code: "FO", prefix: "+298", flag: "🇫🇴" },
  { name: "Îles Heard et McDonald", code: "HM", prefix: "", flag: "🇭🇲" },
  { name: "Îles Malouines", code: "FK", prefix: "+500", flag: "🇫🇰" },
  { name: "Îles Mariannes du Nord", code: "MP", prefix: "+1-670", flag: "🇲🇵" },
  { name: "Îles Marshall", code: "MH", prefix: "+692", flag: "🇲🇭" },
  { name: "Îles Pitcairn", code: "PN", prefix: "+870", flag: "🇵🇳" },
  { name: "Îles Salomon", code: "SB", prefix: "+677", flag: "🇸🇧" },
  { name: "Îles Turques-et-Caïques", code: "TC", prefix: "+1-649", flag: "🇹🇨" },
  { name: "Îles Vierges britanniques", code: "VG", prefix: "+1-284", flag: "🇻🇬" },
  { name: "Îles Vierges des États-Unis", code: "VI", prefix: "+1-340", flag: "🇻🇮" },
  { name: "Inde", code: "IN", prefix: "+91", flag: "🇮🇳" },
  { name: "Indonésie", code: "ID", prefix: "+62", flag: "🇮🇩" },
  { name: "Irak", code: "IQ", prefix: "+964", flag: "🇮🇶" },
  { name: "Iran", code: "IR", prefix: "+98", flag: "🇮🇷" },
  { name: "Irlande", code: "IE", prefix: "+353", flag: "🇮🇪" },
  { name: "Islande", code: "IS", prefix: "+354", flag: "🇮🇸" },
  { name: "Israël", code: "IL", prefix: "+972", flag: "🇮🇱" },
  { name: "Italie", code: "IT", prefix: "+39", flag: "🇮🇹" },
  { name: "Jamaïque", code: "JM", prefix: "+1-876", flag: "🇯🇲" },
  { name: "Japon", code: "JP", prefix: "+81", flag: "🇯🇵" },
  { name: "Jersey", code: "JE", prefix: "+44-1534", flag: "🇯🇪" },
  { name: "Jordanie", code: "JO", prefix: "+962", flag: "🇯🇴" },
  { name: "Kazakhstan", code: "KZ", prefix: "+7", flag: "🇰🇿" },
  { name: "Kenya", code: "KE", prefix: "+254", flag: "🇰🇪" },
  { name: "Kirghizistan", code: "KG", prefix: "+996", flag: "🇰🇬" },
  { name: "Kiribati", code: "KI", prefix: "+686", flag: "🇰🇮" },
  { name: "Koweït", code: "KW", prefix: "+965", flag: "🇰🇼" },
  { name: "Laos", code: "LA", prefix: "+856", flag: "🇱🇦" },
  { name: "Lesotho", code: "LS", prefix: "+266", flag: "🇱🇸" },
  { name: "Lettonie", code: "LV", prefix: "+371", flag: "🇱🇻" },
  { name: "Liban", code: "LB", prefix: "+961", flag: "🇱🇧" },
  { name: "Libéria", code: "LR", prefix: "+231", flag: "🇱🇷" },
  { name: "Libye", code: "LY", prefix: "+218", flag: "🇱🇾" },
  { name: "Liechtenstein", code: "LI", prefix: "+423", flag: "🇱🇮" },
  { name: "Lituanie", code: "LT", prefix: "+370", flag: "🇱🇹" },
  { name: "Luxembourg", code: "LU", prefix: "+352", flag: "🇱🇺" },
  { name: "Macao", code: "MO", prefix: "+853", flag: "🇲🇴" },
  { name: "Macédoine du Nord", code: "MK", prefix: "+389", flag: "🇲🇰" },
  { name: "Madagascar", code: "MG", prefix: "+261", flag: "🇲🇬" },
  { name: "Malaisie", code: "MY", prefix: "+60", flag: "🇲🇾" },
  { name: "Malawi", code: "MW", prefix: "+265", flag: "🇲🇼" },
  { name: "Maldives", code: "MV", prefix: "+960", flag: "🇲🇻" },
  { name: "Mali", code: "ML", prefix: "+223", flag: "🇲🇱" },
  { name: "Malte", code: "MT", prefix: "+356", flag: "🇲🇹" },
  { name: "Maroc", code: "MA", prefix: "+212", flag: "🇲🇦" },
  { name: "Martinique", code: "MQ", prefix: "+596", flag: "🇲🇶" },
  { name: "Maurice", code: "MU", prefix: "+230", flag: "🇲🇺" },
  { name: "Mauritanie", code: "MR", prefix: "+222", flag: "🇲🇷" },
  { name: "Mayotte", code: "YT", prefix: "+262", flag: "🇾🇹" },
  { name: "Mexique", code: "MX", prefix: "+52", flag: "🇲🇽" },
  { name: "Micronésie", code: "FM", prefix: "+691", flag: "🇫🇲" },
  { name: "Moldavie", code: "MD", prefix: "+373", flag: "🇲🇩" },
  { name: "Monaco", code: "MC", prefix: "+377", flag: "🇲🇨" },
  { name: "Mongolie", code: "MN", prefix: "+976", flag: "🇲🇳" },
  { name: "Monténégro", code: "ME", prefix: "+382", flag: "🇲🇪" },
  { name: "Montserrat", code: "MS", prefix: "+1-664", flag: "🇲🇸" },
  { name: "Mozambique", code: "MZ", prefix: "+258", flag: "🇲🇿" },
  { name: "Myanmar", code: "MM", prefix: "+95", flag: "🇲🇲" },
  { name: "Namibie", code: "NA", prefix: "+264", flag: "🇳🇦" },
  { name: "Nauru", code: "NR", prefix: "+674", flag: "🇳🇷" },
  { name: "Népal", code: "NP", prefix: "+977", flag: "🇳🇵" },
  { name: "Nicaragua", code: "NI", prefix: "+505", flag: "🇳🇮" },
  { name: "Niger", code: "NE", prefix: "+227", flag: "🇳🇪" },
  { name: "Nigéria", code: "NG", prefix: "+234", flag: "🇳🇬" },
  { name: "Niue", code: "NU", prefix: "+683", flag: "🇳🇺" },
  { name: "Norvège", code: "NO", prefix: "+47", flag: "🇳🇴" },
  { name: "Nouvelle-Calédonie", code: "NC", prefix: "+687", flag: "🇳🇨" },
  { name: "Nouvelle-Zélande", code: "NZ", prefix: "+64", flag: "🇳🇿" },
  { name: "Oman", code: "OM", prefix: "+968", flag: "🇴🇲" },
  { name: "Ouganda", code: "UG", prefix: "+256", flag: "🇺🇬" },
  { name: "Ouzbékistan", code: "UZ", prefix: "+998", flag: "🇺🇿" },
  { name: "Pakistan", code: "PK", prefix: "+92", flag: "🇵🇰" },
  { name: "Palaos", code: "PW", prefix: "+680", flag: "🇵🇼" },
  { name: "Palestine", code: "PS", prefix: "+970", flag: "🇵🇸" },
  { name: "Panama", code: "PA", prefix: "+507", flag: "🇵🇦" },
  { name: "Papouasie-Nouvelle-Guinée", code: "PG", prefix: "+675", flag: "🇵🇬" },
  { name: "Paraguay", code: "PY", prefix: "+595", flag: "🇵🇾" },
  { name: "Pays-Bas", code: "NL", prefix: "+31", flag: "🇳🇱" },
  { name: "Pérou", code: "PE", prefix: "+51", flag: "🇵🇪" },
  { name: "Philippines", code: "PH", prefix: "+63", flag: "🇵🇭" },
  { name: "Pologne", code: "PL", prefix: "+48", flag: "🇵🇱" },
  { name: "Polynésie française", code: "PF", prefix: "+689", flag: "🇵🇫" },
  { name: "Porto Rico", code: "PR", prefix: "+1-787", flag: "🇵🇷" },
  { name: "Portugal", code: "PT", prefix: "+351", flag: "🇵🇹" },
  { name: "Qatar", code: "QA", prefix: "+974", flag: "🇶🇦" },
  { name: "Réunion", code: "RE", prefix: "+262", flag: "🇷🇪" },
  { name: "Roumanie", code: "RO", prefix: "+40", flag: "🇷🇴" },
  { name: "Royaume-Uni", code: "GB", prefix: "+44", flag: "🇬🇧" },
  { name: "Russie", code: "RU", prefix: "+7", flag: "🇷🇺" },
  { name: "Rwanda", code: "RW", prefix: "+250", flag: "🇷🇼" },
  { name: "Sahara occidental", code: "EH", prefix: "+212", flag: "🇪🇭" },
  { name: "Saint-Barthélemy", code: "BL", prefix: "+590", flag: "🇧🇱" },
  { name: "Saint-Christophe-et-Niévès", code: "KN", prefix: "+1-869", flag: "🇰🇳" },
  { name: "Saint-Marin", code: "SM", prefix: "+378", flag: "🇸🇲" },
  { name: "Saint-Martin", code: "MF", prefix: "+590", flag: "🇲🇫" },
  { name: "Saint-Pierre-et-Miquelon", code: "PM", prefix: "+508", flag: "🇵🇲" },
  { name: "Saint-Vincent-et-les-Grenadines", code: "VC", prefix: "+1-784", flag: "🇻🇨" },
  { name: "Sainte-Hélène", code: "SH", prefix: "+290", flag: "🇸🇭" },
  { name: "Sainte-Lucie", code: "LC", prefix: "+1-758", flag: "🇱🇨" },
  { name: "Salvador", code: "SV", prefix: "+503", flag: "🇸🇻" },
  { name: "Samoa", code: "WS", prefix: "+685", flag: "🇼🇸" },
  { name: "Samoa américaines", code: "AS", prefix: "+1-684", flag: "🇦🇸" },
  { name: "Sao Tomé-et-Principe", code: "ST", prefix: "+239", flag: "🇸🇹" },
  { name: "Sénégal", code: "SN", prefix: "+221", flag: "🇸🇳" },
  { name: "Serbie", code: "RS", prefix: "+381", flag: "🇷🇸" },
  { name: "Seychelles", code: "SC", prefix: "+248", flag: "🇸🇨" },
  { name: "Sierra Leone", code: "SL", prefix: "+232", flag: "🇸🇱" },
  { name: "Singapour", code: "SG", prefix: "+65", flag: "🇸🇬" },
  { name: "Sint Maarten", code: "SX", prefix: "+1-721", flag: "🇸🇽" },
  { name: "Slovaquie", code: "SK", prefix: "+421", flag: "🇸🇰" },
  { name: "Slovénie", code: "SI", prefix: "+386", flag: "🇸🇮" },
  { name: "Somalie", code: "SO", prefix: "+252", flag: "🇸🇴" },
  { name: "Soudan", code: "SD", prefix: "+249", flag: "🇸🇩" },
  { name: "Soudan du Sud", code: "SS", prefix: "+211", flag: "🇸🇸" },
  { name: "Sri Lanka", code: "LK", prefix: "+94", flag: "🇱🇰" },
  { name: "Suède", code: "SE", prefix: "+46", flag: "🇸🇪" },
  { name: "Suisse", code: "CH", prefix: "+41", flag: "🇨🇭" },
  { name: "Suriname", code: "SR", prefix: "+597", flag: "🇸🇷" },
  { name: "Svalbard et Jan Mayen", code: "SJ", prefix: "+47", flag: "🇸🇯" },
  { name: "Syrie", code: "SY", prefix: "+963", flag: "🇸🇾" },
  { name: "Tadjikistan", code: "TJ", prefix: "+992", flag: "🇹🇯" },
  { name: "Taïwan", code: "TW", prefix: "+886", flag: "🇹🇼" },
  { name: "Tanzanie", code: "TZ", prefix: "+255", flag: "🇹🇿" },
  { name: "Tchad", code: "TD", prefix: "+235", flag: "🇹🇩" },
  { name: "Tchéquie", code: "CZ", prefix: "+420", flag: "🇨🇿" },
  { name: "Terres australes françaises", code: "TF", prefix: "", flag: "🇹🇫" },
  { name: "Thaïlande", code: "TH", prefix: "+66", flag: "🇹🇭" },
  { name: "Timor oriental", code: "TL", prefix: "+670", flag: "🇹🇱" },
  { name: "Togo", code: "TG", prefix: "+228", flag: "🇹🇬" },
  { name: "Tokelau", code: "TK", prefix: "+690", flag: "🇹🇰" },
  { name: "Tonga", code: "TO", prefix: "+676", flag: "🇹🇴" },
  { name: "Trinité-et-Tobago", code: "TT", prefix: "+1-868", flag: "🇹🇹" },
  { name: "Tunisie", code: "TN", prefix: "+216", flag: "🇹🇳" },
  { name: "Turkménistan", code: "TM", prefix: "+993", flag: "🇹🇲" },
  { name: "Turquie", code: "TR", prefix: "+90", flag: "🇹🇷" },
  { name: "Tuvalu", code: "TV", prefix: "+688", flag: "🇹🇻" },
  { name: "Ukraine", code: "UA", prefix: "+380", flag: "🇺🇦" },
  { name: "Uruguay", code: "UY", prefix: "+598", flag: "🇺🇾" },
  { name: "Vanuatu", code: "VU", prefix: "+678", flag: "🇻🇺" },
  { name: "Vatican", code: "VA", prefix: "+379", flag: "🇻🇦" },
  { name: "Venezuela", code: "VE", prefix: "+58", flag: "🇻🇪" },
  { name: "Vietnam", code: "VN", prefix: "+84", flag: "🇻🇳" },
  { name: "Wallis-et-Futuna", code: "WF", prefix: "+681", flag: "🇼🇫" },
  { name: "Yémen", code: "YE", prefix: "+967", flag: "🇾🇪" },
  { name: "Zambie", code: "ZM", prefix: "+260", flag: "🇿🇲" },
  { name: "Zimbabwe", code: "ZW", prefix: "+263", flag: "🇿🇼" }
];
