import type { Product, Category, Testimonial } from '@/types';

export const categories: Category[] = [
  {
    id: 'pour-elle',
    name: 'Pour Elle',
    description: 'Vibromasseurs, stimulateurs et accessoires conçus pour la plaisir féminin',
    image: '/category-elle.jpg',
    productCount: 48,
  },
  {
    id: 'pour-lui',
    name: 'Pour Lui',
    description: 'Masturbateurs, anneaux et jouets pour amplifier le plaisir masculin',
    image: '/category-lui.jpg',
    productCount: 36,
  },
  {
    id: 'pour-couples',
    name: 'Pour Couples',
    description: 'Jeux coquins, accessoires partagés pour des moments à deux',
    image: '/category-couples.jpg',
    productCount: 29,
  },
  {
    id: 'bien-etre',
    name: 'Bien-être',
    description: 'Huiles de massage, bougies parfumées pour une ambiance sensuelle',
    image: '/category-bienetre.jpg',
    productCount: 24,
  },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Lumière Rose Gold',
    description: 'Vibromasseur élégant en silicone médical de qualité premium, 10 modes de vibration, rechargeable USB. Design ergonomique pour une stimulation précise.',
    price: 89.99,
    originalPrice: 119.99,
    image: '/product-1.jpg',
    category: 'pour-elle',
    subcategory: 'vibromasseurs',
    rating: 4.8,
    reviews: 127,
    inStock: true,
    isNew: false,
    isBestseller: true,
    tags: ['vibromasseur', 'silicone', 'rechargeable', 'étanche'],
  },
  {
    id: '2',
    name: 'Stimulateur Aurora',
    description: 'Stimulation par ondes de pression et vibrations simultanées, 12 intensités, contrôle tactile. L\'expérience ultime du plaisir.',
    price: 129.99,
    image: '/product-2.jpg',
    category: 'pour-elle',
    subcategory: 'stimulateurs',
    rating: 4.9,
    reviews: 203,
    inStock: true,
    isNew: true,
    tags: ['stimulateur', 'ondes', 'premium', 'silencieux'],
  },
  {
    id: '3',
    name: 'Éclipse Nocturne',
    description: 'Masturbateur masculin haut de gamme avec texture interne réaliste, matériau cyberskin hypoallergénique.',
    price: 69.99,
    originalPrice: 89.99,
    image: '/product-3.jpg',
    category: 'pour-lui',
    subcategory: 'masturbateurs',
    rating: 4.7,
    reviews: 89,
    inStock: true,
    isBestseller: true,
    tags: ['masturbateur', 'realiste', 'premium'],
  },
  {
    id: '4',
    name: 'Anneau Dore',
    description: 'Anneau vibrant rechargeable avec 8 modes de vibration, stretch confortable pour une endurance prolongée.',
    price: 49.99,
    image: '/product-4.jpg',
    category: 'pour-lui',
    subcategory: 'anneaux',
    rating: 4.6,
    reviews: 156,
    inStock: true,
    tags: ['anneau', 'vibrant', 'couple', 'rechargeable'],
  },
  {
    id: '5',
    name: 'Télécommande Secrète',
    description: 'Œuf vibrant télécommandé pour jeux en public, portée 12m, 10 modes, silencieux. L\'excitation à distance.',
    price: 79.99,
    image: '/product-5.jpg',
    category: 'pour-couples',
    subcategory: 'jeux',
    rating: 4.8,
    reviews: 178,
    inStock: true,
    isNew: true,
    tags: ['telecommande', 'oeuf', 'public', 'discret'],
  },
  {
    id: '6',
    name: 'Menottes Velours',
    description: 'Menottes luxueuses en velours avec fermetures sécurisées, confortables et élégantes pour vos jeux de séduction.',
    price: 34.99,
    image: '/product-6.jpg',
    category: 'pour-couples',
    subcategory: 'accessoires',
    rating: 4.9,
    reviews: 234,
    inStock: true,
    isBestseller: true,
    tags: ['menottes', 'velours', 'elegant', 'confort'],
  },
  {
    id: '7',
    name: 'Huile Sensuelle Orchidée',
    description: 'Huile de massage bio aux notes d\'orchidée et vanille, chauffe naturellement au contact de la peau.',
    price: 29.99,
    image: '/product-7.jpg',
    category: 'bien-etre',
    subcategory: 'huiles',
    rating: 4.7,
    reviews: 112,
    inStock: true,
    tags: ['huile', 'massage', 'bio', 'chauffante'],
  },
  {
    id: '8',
    name: 'Bougie Caresse',
    description: 'Bougie de massage qui se transforme en huile chaude, parfum jasmin et santal, 40h de combustion.',
    price: 39.99,
    image: '/product-8.jpg',
    category: 'bien-etre',
    subcategory: 'bougies',
    rating: 4.8,
    reviews: 87,
    inStock: true,
    isNew: true,
    tags: ['bougie', 'massage', 'huile', 'luxueux'],
  },
  {
    id: '9',
    name: 'Vibro Rabbit Luxe',
    description: 'Le classique revisité avec rotation des perles et vibrations du lapin, 3 vitesses, 7 modes.',
    price: 99.99,
    originalPrice: 139.99,
    image: '/product-9.jpg',
    category: 'pour-elle',
    subcategory: 'vibromasseurs',
    rating: 4.6,
    reviews: 312,
    inStock: true,
    isBestseller: true,
    tags: ['rabbit', 'classique', 'rotation', 'vibration'],
  },
  {
    id: '10',
    name: 'Plug Cristal',
    description: 'Plug anal en verre borosilicate avec base en cristal, parfait pour la température play.',
    price: 44.99,
    image: '/product-10.jpg',
    category: 'pour-couples',
    subcategory: 'plugs',
    rating: 4.8,
    reviews: 67,
    inStock: true,
    tags: ['plug', 'verre', 'cristal', 'temperature'],
  },
  {
    id: '11',
    name: 'Stroker Pro',
    description: 'Masturbateur automatique avec 7 modes de succion, chauffage intégré, sensation ultra-réaliste.',
    price: 149.99,
    image: '/product-11.jpg',
    category: 'pour-lui',
    subcategory: 'masturbateurs',
    rating: 4.5,
    reviews: 45,
    inStock: true,
    isNew: true,
    tags: ['automatique', 'succion', 'chauffant', 'premium'],
  },
  {
    id: '12',
    name: 'Galets de Massage',
    description: 'Set de 4 galets en pierre naturelle pour massage sensuel, inclut guide d\'utilisation.',
    price: 24.99,
    image: '/product-12.jpg',
    category: 'bien-etre',
    subcategory: 'accessoires',
    rating: 4.4,
    reviews: 56,
    inStock: true,
    tags: ['pierres', 'massage', 'naturel', 'relaxation'],
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Sophie M.',
    avatar: '/avatar/avatar-1.jpg',
    rating: 5,
    text: 'Livraison ultra discrète comme promise. Le produit est d\'une qualité exceptionnelle, je suis ravie de mon achat. Le service client a été très professionnel.',
    date: '2024-03-15',
  },
  {
    id: '2',
    name: 'Thomas L.',
    avatar: '/avatar/avatar-2.jpg',
    rating: 5,
    text: 'Excellente sélection de produits haut de gamme. Le site est élégant et l\'expérience d\'achat très agréable. Je recommande vivement !',
    date: '2024-03-10',
  },
  {
    id: '3',
    name: 'Marie & Julien',
    avatar: '/avatar/avatar-3.jpg',
    rating: 5,
    text: 'Nous avons découvert cette boutique ensemble et nous sommes conquis. Les produits pour couples sont vraiment bien pensés. Merci !',
    date: '2024-03-05',
  },
  {
    id: '4',
    name: 'Camille R.',
    avatar: '/avatar/avatar-4.jpg',
    rating: 5,
    text: 'Le packaging est luxueux, parfait pour offrir. La qualité des matériaux est au rendez-vous. Une vraie découverte !',
    date: '2024-02-28',
  },
  {
    id: '5',
    name: 'Alexandre D.',
    avatar: '/avatar/avatar-5.jpg',
    rating: 4,
    text: 'Très satisfait de ma commande. Livraison rapide et discrète. Les produits correspondent parfaitement à la description.',
    date: '2024-02-20',
  },
];

export const navLinks = [
  { label: 'Accueil', href: '#accueil' },
  { label: 'Collection', href: '#collection' },
  { label: 'Nouveautés', href: '#nouveautes' },
  { label: 'À propos', href: '/about' },
];
